### ISSUE TITLE
No obvious way to exit without starting sessions

### ISSUE THREAD

**Issue by captainwasabi** [iasj/IniTmux#3]
I need to be able to do this because I start sessions as different users and might need to bail if what I need is not listed.

Note: CTRL-C just opens everything.  If you enter a non-existent number (like 99) then it exits properly.    I think CTRL-C should probably exit and a non existent number should just ask which one you want again.

**Comment by iasj** [comment]
Hello @captainwasabi. Thanks for your interaction. I've added some half measure fixing by adding another item in the main menu (very busy). Now it opens like this:

```console
Select Sessions [0 1 2 ...]:

    [0] AK-Data
    [1] AK-Features
    [2] AK-Math
    [3] AK-Home
    [4] Files
    [5] IniTmux
    [6] Library
    [7] Misc
    [8] ping
    [9] Organizer
    [10] Packagers
    [11] Project
    [12] Studies
    [13] Test
    [14] Youtube-DL

    [x] Exit

Create All Sessions [Enter To Choose All]?
```

so, if you press x or X, it will exit the way you need. 

I might add (in my defense) that this code was written very quickly because I was needing this functionality back then. Anyway, I never had the time to polish this code up. Next version will have an Object Oriented approach, but I can't promiss this until the end of this year.

Thanks for using it, and I hope this helps!

**Comment by captainwasabi** [comment]
No defense needed!! Thank you for making this available!
