### ISSUE TITLE
The real issues ;)

### ISSUE THREAD

**Issue by captainwasabi** [iasj/IniTmux#4]
ok, 
- I think you should use python3 in the shebang.  Lots of people, including me, have python2 installed because there is existing code that needs to work.  I'll get around to converting it to 3 in a year or two. ;)
- Drop the following code in and it'll handle CTRL-C cleaner than a stack trace ;)

```
#Handler for Crtl-C
import signal
def signal_handler(signal, frame):
    #print("\nYou pressed Ctrl+C, exiting!\n")
    #call('clear')
    sys.exit()
signal.signal(signal.SIGINT, signal_handler)
```
- Ok, if I understand it correctly, if I load item 11, then attack and delete a window, then detach.  If I load 11 again it should put the window back the way it was originally. What is happening is that if I delete window 6, then load 11, window 5 gets and extra pane and window 6 just gets one pane.

Besides that it seems to be working fine.

**Comment by iasj** [comment]
Ok, let me try to explain what I did and other things as well:

1) I was using #!/usr/bin/env python as shebang 'cause I use Arch Linux, and python3 comes by default on it. But, yeah, I've changed it to #!/usr/bin/python3 so people can see it works only for python 3. Thanks for that!

2) The Ctrl-C handler didn't work. I'm not really sure where should I put those lines. I'm afraid the order is important. Now they are commented.

3) I lack the time right now to try your use case, but this behaviour might be happening because I did not implement everything yet. Like I said, I was in a hurry to get this program running when I made it. Like the name of it suggests, this software only supports [init]ialization for t[mux], and saving in yaml files as well. But still, I have good plans for it. First step will tide the code up to Object Oriented programming so I can manage bugs easier. After that, I'll start to implement some sort of "check" methods, to check if some session, window or pane is already loaded, killed, etc. This way, whenever you run it again, It will place things right in their places. 

Here is a short list of functionalities I intend to do:

```text
- O.O. coding (The code is a mess!)
- Better versioning system (Version 3.2.3, etc)
- Argument Parsing 
- Default models in yaml default files.
- Check, save and reload methods for sessions
- Split documentation in a wiki rather than a single README.md
``` 

there are other things I don't remember right now.

**Comment by captainwasabi** [comment]
1) cool

2) hmm, I think it should just work.  Where you put it should be fine. 

3) Definitely no worries.   This fits my bill 100% as is, and it even works perfectly on my phone and tablet. :) Thank you very much for making it available. I was just trying to test other features just because they were there.

Note: I'd get rid of that try/except around the import of getoutput, or maybe just make the catch output "are you sure you're running this with python 3? ;) I looked in the official 3.5 docs and don't see anything about it being deprecated.  I think it might have just been moved from the command module in < 2.6 to the subprocess module and that is where it was deprecated.  It definitely works in 3.4 & 3.5. (Which may be another issue, Ubuntu 14.04 is LTS so it's stuck on Python 3.4.  I haven't moved my servers to 16.04 yet (and probably wont for a couple of years, I just moved them to 14.04 earlier this year)

**Comment by iasj** [comment]
OMG!

Phone and tablet. That's new for me. That's why you manage to use a lot of users I suppose.

You should try Arch Linux. It is rolling release, perfect package building system, a wiki that teachs you Linux, etc.

**Comment by captainwasabi** [comment]
all my servers are belong to ubuntu LTS ;)
OTOH, I expect that there is not that much difference.  I'm a server CLI guy.

Btw, the crtl-c handler just needs "import sys" for sys.exit(0) to work. (at least with 3.4.1).  

The only time placement of the 
```
    signal.signal(signal.SIGINT, signal_handler)

```
matters is if you want to turn it on and off with:

```
    signal.signal(signal.SIGINT, signal.SIG_DFL) #sets it back to the default, or

    signal.signal(signal.SIGINT, signal.SIG_IGN) #completely ignores the signal
```

Yeah, Android phones/tablets have an app "Termux" that gives you a user bash shell.

**Comment by iasj** [comment]
Yeah, I'm so stupid. How could I forget to import sys. Thanks again.
