### ISSUE TITLE
session creation issues

### ISSUE THREAD

**Issue by captainwasabi** [iasj/IniTmux#5]
ok, it looks like the first window created is :1 not :0

This affects line 61:

```
    Command = 'tmux rename-window -t '+SName+':0 '+WName
```

to

```
    Command = 'tmux rename-window -t '+SName+':1 '+WName
```

There are other creation issues it seems, and I'll just add them to this issue

**Comment by captainwasabi** [comment]
It also affects lines 380 & 381
```
    NewWindow(SName,WName,WNumber)
    CreatePanes(SName,WName,WNumber,Root,Model,SpecificDir,SpecificLayout)
```
to
```
    NewWindow(SName,WName,WNumber**+1**)
    CreatePanes(SName,WName,WNumber**+1**,Root,Model,SpecificDir,SpecificLayout)
```

**Comment by captainwasabi** [comment]
tmux version 1.8, looks like the latest version is 2.2

**Comment by captainwasabi** [comment]
tracked it down.  I had this line in my .tmux.conf
```
    # Start tab numbering at 1
    set -g base-index 1
```

looking to see if there is a way to retrieve that info

**Comment by captainwasabi** [comment]
I just set it to 0.  I seem to still be having problem with the command for the first panel overrides the window name that was set

**Comment by iasj** [comment]
Hello again. Well, for my shame I have no idea why this is happening. Such a difficult bug to track. [This is my tmux configuration](https://github.com/iasj/tmux). Try to compare with yours. 

Note that I  have neither "set -g base-index 1" nor "set -g base-index 0" in it. I think the default value for it is zero.

And, referring to this bug itself... well, I think the root of it is in the function NewWindow, once is the only place where occurs window creation. The following lines

```python
    if WNumber > 0:
        Command = 'tmux new-window -n '+WName+' -t '+SName
    else:
        Command = 'tmux rename-window -t '+SName+':0 '+WName
```

in the function NewWindow is the problem, but I can't solve it because I'm not sure how your use case really is.

Well, those bugs are motivating me to make those changes I mentioned. I'll take some time, from now on, to start them.

Ping me if find anything, good luck!

**Comment by captainwasabi** [comment]
as far as I can tell 100% of my problem is tmux being behind by a major version update.  I did additional testing on my phone and tablet which use 2.2 and everything seems to work perfect.

**Comment by iasj** [comment]
Well, meybe this might be the problem yes. But I'll start to work on Initmux anyway. I'm planing to make changes on directory structure inside `~/.config/Initmux`. It will something like this:

```text
~/.config/initmux
|__ layouts/
|__ models.yml
|__ config.yml
```

and more things. In this case, you will have to put your yml files inside layouts directory. This directory will store categories and layouts, respectively. I need this feature because I have a lot of yml files and the initial menu it growing big. So, with this new feature it will be possible to choose the category first and then choose you yml file sessions.

The file models.yml will have a set of models you want to use in a lot of yml files. The config.yml file for default configurations, etc. That's why I'm planing to insert argument parser feature. I'll put commands like these: `initmux new yml`, `initmux edit`

and then initmux will open a menu for you to choose the category, yml file, etc with your default text editor defined in config.yml.

What do you think? Do you have some ideas you want to share? And something that could help me is to know how people are using initmux. Can you share you yml files, I think I could more use cases.
